site_name: Cobra Commander - Ruby
site_description: Cobra Commander Ruby Documentation
repo_url: https://github.com/powerhome/cobra_commander
nav:
  - "Home": "README.md"
  - "Changelog": "CHANGELOG.md"
plugins:
  - techdocs-core
