# frozen_string_literal: true

source "https://rubygems.org"

path "components" do
  gem "authn"
  gem "authz"
  gem "hr"
  gem "sales"
end

gem "finance", path: "components/finance"

gem "useragent"
