require:
  - rubocop-powerhome

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
