require:
  - rubocop-powerhome

Rails:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'gemfiles/*'

Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*'
