# frozen_string_literal: true

source "https://rubygems.org"

gemspec

bundler_version = ENV.fetch("BUNDLER_VERSION", "2")
gem "bundler", "~> #{bundler_version}"

group :cobra do
  gem "cobra_commander-stub", path: "./spec/support/", require: "stub_source"
end
