# frozen_string_literal: true

source "https://rubygems.org"

gemspec

bundler_version = ENV.fetch("BUNDLER_VERSION", "2")
gem "bundler", "~> #{bundler_version}"

gem "cobra_commander-ruby", path: "../"
gem "cobra_commander-yarn", path: "../"
