name: CI

on: push

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
        bundler:
          - "1"
          - "2"
    env:
      BUNDLE_GEMFILE: gemfiles/bundler${{ matrix.bundler }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: ${{ matrix.bundler }}
        bundler-cache: true
    - name: Install bundler v1 # Even if we're testing bundler v2, we need v1 available because the fixture components have it in their Gemfile.locks
      run: gem install bundler -v "~> 1" --no-document
    - name: Install Graphviz
      run: sudo apt -qq install graphviz
    - name: Run tests
      run: bundle exec rake spec
  lint:
    name: Lint Ruby
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - uses: reviewdog/action-rubocop@v2
      with:
        rubocop_version: 0.88.0
        filter_mode: nofilter
        fail_on_error: true
        rubocop_extensions: ""
        github_token: ${{ secrets.github_token }}
