name: cobra_commander-ruby

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@0b860c8a7af141ebb16db41acba4eb86776b57bf # main
    with:
      package: '${{ github.workflow }}'
      workdir: '${{ github.workflow }}'
      ruby: '["3.2","3.3","3.4","4.0"]'
    secrets: inherit
