name: cobra_commander

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@main
    with:
      package: '${{ github.workflow }}'
      workdir: '${{ github.workflow }}'
    secrets: inherit
