name: cobra_commander

on:
  push:

jobs:
  ruby:
    uses: powerhome/power-tools/.github/workflows/_ruby-workflow.yml@main
    with:
      package: '${{ github.workflow }}'
      workdir: '${{ github.workflow }}'
      bundler: '["1.17.3", "2.4.17"]'
      gemfiles: |-
        [
          "gemfiles/bundler_1.gemfile",
          "gemfiles/bundler_2.gemfile",
        ]
      exclude: |-
        [
          { gemfile: "gemfiles/bundler_1.gemfile", bundler: "2.4.17" },
          { gemfile: "gemfiles/bundler_2.gemfile", bundler: "1.17.3" }
        ]
    secrets: inherit
