name: cobra_commander-yarn

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@bd38636f54897c992d5b09a86c86707e4b5b7734 # main
    with:
      package: '${{ github.workflow }}'
      workdir: '${{ github.workflow }}'
      ruby: '["3.2","3.3","3.4","4.0"]'
    secrets: inherit
