name: cobra_commander

on:
  push:

jobs:
  ruby:
    uses: powerhome/power-tools/.github/workflows/_ruby-workflow.yml@main
    with:
      package: '${{ github.workflow }}'
      workdir: '${{ github.workflow }}'
      gemfiles: '["gemfiles/bundler-1.gemfile","gemfiles/bundler-2.gemfile"]'
      bundler: '["1", "2"]'
      exclude: |-
        [
          { gemfile: "gemfiles/bundler-1.gemfile", bundler: "2" },
          { gemfile: "gemfiles/bundler-2.gemfile", bundler: "1" }
        ]
    secrets: inherit
