name: cobra_commander

on:
  push:

jobs:
  ruby:
    uses: powerhome/power-tools/.github/workflows/_ruby-workflow.yml@main
    with:
      package: '${{ github.workflow }}'
      workdir: '${{ github.workflow }}'
    secrets: inherit
