name: cobra_commander-ruby

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@5863b64d44ea6a59869f11f5880a5531b6b9f0d6 # main
    with:
      package: '${{ github.workflow }}'
      workdir: '${{ github.workflow }}'
      ruby: '["3.2","3.3","3.4","4.0"]'
    secrets: inherit
