name: cobra_commander

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@fac890a4a3a619cc2f0b16813714603cc2e71a14 # main
    with:
      package: '${{ github.workflow }}'
      workdir: '${{ github.workflow }}'
      ruby: '["3.2","3.3","3.4","4.0"]'
    secrets: inherit
