name: cobra_commander-yarn

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@cbcd3136be871ebab1c0f3dcb32fdc178fbac50b # main
    with:
      package: '${{ github.workflow }}'
      workdir: '${{ github.workflow }}'
      ruby: '["3.2","3.3","3.4","4.0"]'
    secrets: inherit
